services:
  mysql:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: hr
    ports:
      - "3306:3306" 
    volumes:
      - .my/sql-data:/var/lib/mysql
